import type { Metadata } from "next";
import { Cinzel_Decorative, Raleway } from "next/font/google";
import "./globals.css";

export const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["700"],
});

export const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="background-columns">
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
          <div className="column"></div>
        </div>

        <div className="content">{children}</div>
      </body>
    </html>
  );
}
